const Questions = [
    {
      ques: "HTML stand for ___",
      a: "hyper text markup language",
      b: "hyper text mark language",
      c: "hyper text marks language",
      d: "hyper text mark language",
      correct: "a",
    },
    {
      ques: "Which one of the following is not a semantic tag?",
      a: "footer",
      b: "div",
      c: "header",
      d: "nav",
      correct: "b",
    },
    {
      ques: "Largest heading in HTML5?",
      a: "h2",
      b: "h5",
      c: "h6",
      d: "h1",
      correct: "d",
    },
    {
    ques: "Which tag is used to create a hyperlink in HTML?",
    a: "link",
    b: "a",
    c: "href",
    d: "hyper",
    correct: "b",
    },
    {
    ques: "Which HTML attribute is used to define inline styles?",
    a: "class",
    b: "font",
    c: "style",
    d: "styles",
    correct: "c",
    },
    {
    ques: "Which HTML element is used to define the structure of a table row?",
    a: "tabl",
    b: "td",
    c: "tr",
    d: "th",
    correct: "c",
    },
    {
    ques: "What is the correct HTML element for inserting a line break?",
    a: "break",
    b: "lb",
    c: "br",
    d: "hr",
    correct: "c",
    },
    {
    ques: "Which tag is used to define a list item in an ordered or unordered list?",
    a: "li",
    b: "ul",
    c: "ol",
    d: "list",
    correct: "a",
    },
    {
    ques: "What does the 'alt' attribute in an <img> tag specify?",
    a: "Image alignment",
    b: "Alternate image source",
    c: "Image size",
    d: "Alternate text for the image",
    correct: "d",
    },
    {
    ques: "Which HTML tag is used to display a horizontal rule?",
    a: "line",
    b: "hr",
    c: "br",
    d: "rule",
    correct: "b",
    },
];
